site_name: "ContainerSSH: Launch containers on demand"
site_description: "ContainerSSH is a standalone, customizable SSH server that launches containers in Kubernetes or Docker"
site_url: "https://containerssh.io/"
repo_url: "https://github.com/containerssh/containerssh.github.io/"
edit_uri: "edit/main/docs/"
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - meta
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: True
      separator: "-"
theme:
  name: material
  custom_dir: .docs-theme
  palette:
    primary: blue
    accent: blue
  font: false
  features:
    - navigation.tabs
    - toc.autohide
    - search.suggest
    - search.highlight
  logo: images/logo.svg
  favicon: images/logo.svg
  language: en
  include_search_page: false
  search_index_only: 'false'
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/CFMMqwS
      name: Discord
    - icon: fontawesome/brands/github
      link: https://github.com/ContainerSSH
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ContainerSSH
      name: Twitter
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/containerssh
      name: Docker Hub
plugins:
  - search
  - macros
  - awesome-pages
  - blog:
      format: ""
  - redirects:
      redirect_maps:
        'ssh.md': 'development/containerssh/ssh.md'
        'developing.md': 'development/index.md'
        'contributing/index.md': 'development/index.md'
        'contributing/internal-architecture.md': 'development/containerssh/internal-architecture.md'
        'development/internal-architecture.md': 'development/containerssh/internal-architecture.md'
        'contributing/libraries.md': 'development/dashboard.md'
        'contributing/roadmap.md': 'development/dashboard.md'
        'quickstart.md': 'getting-started/index.md'
        'installation.md': 'getting-started/installation.md'
        'authserver.md': 'getting-started/authserver.md'
        'configuration.md': 'getting-started/configuration.md'
        'configserver.md': 'getting-started/configserver.md'
        'backends.md': 'getting-started/backends/index.md'
        'dockerrun.md': 'getting-started/backends/dockerrun.md'
        'kuberun.md': 'getting-started/backends/kuberun.md'
        'faq.md': 'getting-started/faq.md'
        'audit/index.md': 'advanced/audit/index.md'
        'audit/format.md': 'advanced/audit/format.md'
        'license.md': 'about/license.md'
        'imprint.md': 'about/imprint.md'
        'privacy.md': 'about/privacy.md'
site_favicon: img/favicon.png
extra_css:
  - css/custom.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascript/tables.js
copyright: >
  Copyright &copy; <a href="/about/">ContainerSSH Contributors</a>
  | <a href="/about/">About</a>
  | <a href="/about/license/">MIT license</a>
  | <a href="https://github.com/ContainerSSH/branding/blob/main/README.md">Brand assets</a>
  | <a href="/about/privacy/">Privacy Policy</a>
  | <a href="/about/imprint/">Imprint</a>