site_name: "ContainerSSH: Launch containers on demand"
site_description: "ContainerSSH is a standalone, customizable SSH server that launches containers in Kubernetes or Docker"
site_url: "https://containerssh.github.io/"
repo_url: "https://github.com/containerssh/containerssh.github.io/"
edit_uri: "edit/main/docs/"
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: True
      separator: "-"
theme:
  name: material
  custom_dir: .docs-theme
  palette:
    primary: blue
    accent: blue
  font: false
  features:
    - navigation.tabs
    - toc.autohide
    - search.suggest
    - search.highlight
  logo: images/logo.svg
  favicon: images/logo.svg
  language: en
  include_search_page: false
  search_index_only: 'false'
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/CFMMqwS
      name: Discord
    - icon: fontawesome/brands/github
      link: https://github.com/ContainerSSH
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ContainerSSH
      name: Twitter
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/containerssh
      name: Docker Hub
plugins:
  - search
  - macros
nav:
  - 'Home': 'index.md'
  - 'Use cases':
      - Web hosting: 'usecases/webhosting.md'
      - Learning environments: 'usecases/learning.md'
      - Honeypots: 'usecases/honeypots.md'
      - Security: 'usecases/security.md'
  - 'Getting started':
    - 'Quick Start': 'quickstart.md'
    - 'Installation': 'installation.md'
    - 'Configuration': 'configuration.md'
    - 'Authentication Server': 'authserver.md'
    - 'Configuration Server': 'configserver.md'
    - 'Selecting a Backend': 'backends.md'
    - 'The dockerrun Backend': 'dockerrun.md'
    - 'The kuberun Backend': 'kuberun.md'
    - FAQ: 'faq.md'
  - 'Advanced usage':
    - 'Creating an Image': 'image.md'
    - 'Logging': 'logging.md'
    - 'Metrics': 'metrics.md'
    - 'Hardening': 'hardening.md'
    - 'Audit logging':
      - 'Audit logging': 'audit/index.md'
      - 'Log format': 'audit/format.md'
    - 'Developing': 'developing.md'
  - APIs:
      - 'About the API': 'api/index.md'
      - 'The AuthConfig Server ⭧': './api/authconfig/'
site_favicon: img/favicon.png
extra_css:
  - css/custom.css
copyright: >
  Copyright &copy; ContainerSSH Contributors
  | <a href="https://containerssh.github.io/privacy/">Privacy Policy</a>