name: Deploy website
on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches-ignore:
      - 'gh-pages'
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install OS packages
        run: sudo apt update && sudo apt install -y libffi-dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Build
        run: mkdocs build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: |
            site/*
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: site
      - name: Deploy
        run: |
          cd site && \
          git init && \
          git config user.name "GitHub Actions" && \
          git config user.email noreply@github.com && \
          git remote add origin https://containerssh:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git && \
          git add . && \
          git commit -m "Website publish" && \
          git checkout -b gh-pages && \
          git push --set-upstream --force origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}